CREATE TABLE IF NOT EXISTS shoot_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT DEFAULT '',
  address TEXT DEFAULT '',
  category TEXT DEFAULT '新築',
  "furnitureSetup" TEXT DEFAULT 'なし',
  "customerName" TEXT DEFAULT '',
  "customerLat" TEXT DEFAULT '',
  "customerLon" TEXT DEFAULT '',
  "mainStore" TEXT DEFAULT '',
  "googleMapUrl" TEXT DEFAULT '',
  "eventName" TEXT DEFAULT '',
  "setupDate" TEXT DEFAULT '',
  "setupEndTime" TEXT DEFAULT '',
  "setupVehicle" TEXT DEFAULT '',
  "setupVehicle2" TEXT DEFAULT '',
  "teardownDate" TEXT DEFAULT '',
  "teardownEndTime" TEXT DEFAULT '',
  "teardownVehicle" TEXT DEFAULT '',
  "teardownVehicle2" TEXT DEFAULT '',
  "shootingRangeFrom" TEXT DEFAULT '',
  "shootingRangeTo" TEXT DEFAULT '',
  "openHouseDate" TEXT DEFAULT '',
  "openHouseDates" JSONB DEFAULT '[]',
  "handoverDate" TEXT DEFAULT '',
  "handoverSource" TEXT DEFAULT '',
  "youtubeDate" TEXT DEFAULT '',
  "youtubeStartTime" TEXT DEFAULT '',
  "youtubeEndTime" TEXT DEFAULT '',
  "youtubeStaff" JSONB DEFAULT '[]',
  "youtubeRequested" BOOLEAN DEFAULT false,
  "youtubeNote" TEXT DEFAULT '',
  "photoDate" TEXT DEFAULT '',
  "photoStartTime" TEXT DEFAULT '',
  "photoEndTime" TEXT DEFAULT '',
  "photoStaff" JSONB DEFAULT '[]',
  "photoRequested" BOOLEAN DEFAULT false,
  "photoNote" TEXT DEFAULT '',
  "exteriorPhotoDate" TEXT DEFAULT '',
  "exteriorPhotoStartTime" TEXT DEFAULT '',
  "exteriorPhotoEndTime" TEXT DEFAULT '',
  "exteriorPhotoStaff" JSONB DEFAULT '[]',
  "exteriorPhotoRequested" BOOLEAN DEFAULT false,
  "exteriorPhotoNote" TEXT DEFAULT '',
  "instaLiveDate" TEXT DEFAULT '',
  "instaLiveStartTime" TEXT DEFAULT '',
  "instaLiveEndTime" TEXT DEFAULT '',
  "instaLiveStaff" JSONB DEFAULT '[]',
  "instaLiveRequested" BOOLEAN DEFAULT false,
  "instaLiveNote" TEXT DEFAULT '',
  "instaRegularDate" TEXT DEFAULT '',
  "instaRegularStartTime" TEXT DEFAULT '',
  "instaRegularEndTime" TEXT DEFAULT '',
  "instaRegularStaff" JSONB DEFAULT '[]',
  "instaRegularRequested" BOOLEAN DEFAULT false,
  "instaRegularNote" TEXT DEFAULT '',
  "instaPromoDate" TEXT DEFAULT '',
  "instaPromoStartTime" TEXT DEFAULT '',
  "instaPromoEndTime" TEXT DEFAULT '',
  "instaPromoStaff" JSONB DEFAULT '[]',
  "instaPromoRequested" BOOLEAN DEFAULT false,
  "instaPromoNote" TEXT DEFAULT '',
  "otherDate" TEXT DEFAULT '',
  "otherStartTime" TEXT DEFAULT '',
  "otherEndTime" TEXT DEFAULT '',
  "otherStaff" JSONB DEFAULT '[]',
  "otherRequested" BOOLEAN DEFAULT false,
  "otherNote" TEXT DEFAULT '',
  "notificationStaff" JSONB DEFAULT '[]',
  "systemId" TEXT DEFAULT '',
  "salesRep" TEXT DEFAULT '',
  "icRep" TEXT DEFAULT '',
  "constructionRep" TEXT DEFAULT '',
  requester TEXT DEFAULT '',
  "shootingTypes" JSONB DEFAULT '[]',
  "parkingInfo" TEXT DEFAULT '',
  "shootingPoints" TEXT DEFAULT '',
  "witnessStaff" TEXT DEFAULT '',
  "ownerPresence" TEXT DEFAULT '',
  "instructionFileUrl" TEXT DEFAULT '',
  "instructionFileName" TEXT DEFAULT '',
  "overviewFileUrl" TEXT DEFAULT '',
  "overviewFileName" TEXT DEFAULT '',
  "shootingNotes" TEXT DEFAULT '',
  "contractDate" TEXT DEFAULT '',
  "contractAmount" TEXT DEFAULT '',
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS shoot_logs_systemid_unique ON shoot_logs ("systemId") WHERE "systemId" != '';

ALTER TABLE shoot_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to shoot_logs" ON shoot_logs FOR ALL USING (true) WITH CHECK (true);
ALTER publication supabase_realtime ADD TABLE shoot_logs;
