-- イベントテーブルに基本情報・ANDPAD連携フィールドを追加
ALTER TABLE events ADD COLUMN IF NOT EXISTS "customerName" TEXT DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS "googleMapUrl" TEXT DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS "systemId" TEXT DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS "salesRep" TEXT DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS "icRep" TEXT DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS "constructionRep" TEXT DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS "eventName" TEXT DEFAULT '';
ALTER TABLE events ADD COLUMN IF NOT EXISTS "handoverDate" TEXT DEFAULT '';
