ALTER TABLE properties ADD COLUMN IF NOT EXISTS "setupEndTime" TEXT DEFAULT '';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS "teardownEndTime" TEXT DEFAULT '';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS "setupVehicle2" TEXT DEFAULT '';
ALTER TABLE properties ADD COLUMN IF NOT EXISTS "teardownVehicle2" TEXT DEFAULT '';
