// ANDPAD CSV/XLSXカラム → DBカラムのマッピング定義

export interface ColumnMapping {
  csvColumn: string
  dbColumn: string
}

// 案件テーブルのカラムマッピング
export const DEALS_MAPPINGS: Record<string, string> = {
  // 基本情報
  'システムID': 'andpad_id',
  '案件管理ID': 'management_id',
  '問合番号': 'inquiry_number',
  '案件名': 'name',
  '顧客ID': 'customer_andpad_id',
  '顧客名': 'customer_name',
  '案件種別': 'deal_category',
  '案件区分': 'deal_type',
  '案件フロー': 'deal_flow',
  '案件ワークフロー': 'deal_workflow',
  '案件作成者': 'deal_creator',
  '案件作成日時': 'deal_created_at',
  '契約番号': 'contract_number',
  '本契約番号': 'main_contract_number',
  '引合状況': 'status',
  '成約確度': 'closing_probability',
  // 店舗・担当
  '主担当店舗': 'store_name',
  '主担当': 'staff_name',
  '役割:営業': 'role_sales',
  '役割:設計': 'role_design',
  '役割:工事': 'role_construction',
  '役割:インテリアコーディネーター': 'role_ic',
  '役割:施工管理補助①': 'role_construction_sub1',
  '役割:施工管理補助②': 'role_construction_sub2',
  '役割:その他': 'role_other',
  '役割:営業補助': 'role_sales_sub',
  '役割:EX事業部': 'role_ex',
  // 反響・営業
  '反響種別': 'response_type',
  '反響元': 'source',
  '反響日': 'inquiry_date',
  '受付者': 'receptionist',
  '希望工事予算': 'desired_budget',
  '施工きっかけ': 'construction_trigger',
  // 売上見込
  '売上見込 売上(税込)': 'estimate_amount',
  '売上見込 売上(税抜)': 'estimate_amount_ex_tax',
  '売上見込 原価': 'estimate_cost',
  '売上見込 粗利額': 'estimate_gross_profit',
  '売上見込 粗利率': 'estimate_gross_profit_rate',
  // 工事
  '工事場所': 'construction_location',
  '工事種類': 'category',
  '工事内容': 'construction_content',
  // 失注
  '失注種別': 'lost_type',
  '失注日': 'lost_date',
  '失注理由': 'lost_reason',
  // 日程
  '初回面談日(予定)': 'meeting_date_planned',
  '初回面談日(実績)': 'meeting_date',
  '初回訪問日(予定)': 'visit_date_planned',
  '初回訪問日(実績)': 'visit_date_actual',
  '現調日(予定)': 'survey_date_planned',
  '現調日(実績)': 'survey_date_actual',
  '初回プラン提出(予定)': 'plan_submit_date_planned',
  '初回プラン提出(実績)': 'plan_submit_date_actual',
  '耐震申込日(予定)': 'seismic_date_planned',
  '耐震申込日(実績)': 'seismic_date_actual',
  '設計申込日(予定)': 'design_date_planned',
  '設計申込日(実績)': 'design_date_actual',
  '契約日(予定)': 'order_date_planned',
  '契約日(実績)': 'order_date',
  '着工日(予定)': 'start_date_planned',
  '着工日(実績)': 'start_date',
  '上棟日(予定)': 'topping_date_planned',
  '上棟日(実績)': 'topping_date_actual',
  '完成日(予定)': 'completion_date_planned',
  '完成日(実績)': 'completion_date',
  '引渡日(予定)': 'handover_date_planned',
  '引渡日(実績)': 'handover_date_actual',
  // ラベル
  'ラベル:施工エリア': 'label_area',
  'ラベル:営業所': 'label_office',
  'ラベル:工事分類': 'label_construction_type',
  // 移行用
  '移行用:SAKSAK顧客コード': 'migration_saksak_customer',
  '移行用:SAKSAK問合番号': 'migration_saksak_inquiry',
  '移行用:SAKSAK契約番号': 'migration_saksak_contract',
  '移行用:ダンドリワーク現場ID': 'migration_dandori_id',
  '移行用:店舗名': 'migration_store',
  '移行用:工事分類': 'migration_construction_type',
  '移行用:問合項目ー工事種類': 'migration_inquiry_type',
  '移行用:プラン契約番号': 'migration_plan_contract',
  // 入金
  '入金:状態': 'payment_status',
  '入金:契約日': 'payment_contract_date',
  '入金:着工日': 'payment_start_date',
  '入金:完成日': 'payment_completion_date',
  '入金:引渡日': 'payment_handover_date',
  // 契約時
  '契約時:売上金額（税込）': 'order_amount',
  '契約時:売上金額（税抜）': 'contract_amount_ex_tax',
  '契約時:原価': 'contract_cost',
  '契約時:予備原価': 'contract_reserve_cost',
  '契約時:粗利': 'contract_gross_profit',
  '契約時:粗利率': 'contract_gross_profit_rate',
  // 実行予算確定時
  '実行予算確定時:売上金額（税込）': 'budget_amount_inc_tax',
  '実行予算確定時:売上金額（税抜）': 'budget_amount_ex_tax',
  '実行予算確定時:原価': 'budget_cost',
  '実行予算確定時:予備原価': 'budget_reserve_cost',
  '実行予算確定時:粗利': 'budget_gross_profit',
  '実行予算確定時:粗利率': 'budget_gross_profit_rate',
  // 進行中
  '進行中:売上金額（税込）': 'progress_amount_inc_tax',
  '進行中:売上金額（税抜）': 'progress_amount_ex_tax',
  '進行中:原価': 'progress_cost',
  '進行中:予備原価': 'progress_reserve_cost',
  '進行中 粗利額': 'progress_gross_profit',
  '進行中 粗利率': 'progress_gross_profit_rate',
  // 精算完了時
  '精算完了時:売上金額（税込）': 'settlement_amount_inc_tax',
  '精算完了時:売上金額（税抜）': 'settlement_amount_ex_tax',
  '精算完了時:原価': 'settlement_cost',
  '精算完了時:予備原価': 'settlement_reserve_cost',
  '精算完了時:粗利': 'settlement_gross_profit',
  '精算完了時:粗利率': 'settlement_gross_profit_rate',
  // 税率
  '税率': 'tax_rate',
}

// 案件XLSXの顧客カラム → customersテーブルカラムのマッピング
export const DEALS_CUSTOMER_COLUMN_MAP: Record<string, string> = {
  '顧客ID': 'andpad_id',
  '顧客管理ID': 'management_id',
  '種別': 'customer_type',
  '顧客名': 'name',
  '顧客名 敬称': 'name_title',
  '顧客名（カナ）': 'name_kana',
  '顧客名2': 'name2',
  '顧客名2 敬称': 'name2_title',
  '顧客名2（カナ）': 'name2_kana',
  '顧客郵便番号': 'postal_code',
  '顧客都道府県': 'prefecture',
  '顧客現住所': 'address',
  '顧客緯度': 'latitude',
  '顧客経度': 'longitude',
  '顧客担当者名': 'contact_name',
  '顧客担当者名（カナ）': 'contact_name_kana',
  '顧客電話番号1': 'phone1',
  '顧客電話番号2': 'phone2',
  '顧客メールアドレス': 'email',
  '顧客FAX': 'fax',
  '顧客ランク': 'rank',
  '顧客分類': 'classification',
  '担当者所属店舗': 'staff_store',
  '担当者': 'staff_name',
  'DMの可否': 'dm_allowed',
}
